# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 08:26
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_my',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('article_name', models.CharField(max_length=30, verbose_name='文章名字')),
                ('article_author', models.CharField(max_length=20, verbose_name='作者')),
                ('article_count', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容')),
                ('article_img', models.ImageField(default='myimg/starlu.png', upload_to='article', verbose_name='文章图片')),
                ('article_title', ckeditor_uploader.fields.RichTextUploadingField(max_length=100, verbose_name='文章简介')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Article_pl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('pl_name', models.CharField(max_length=30, verbose_name='评论昵称')),
                ('pl_eml', models.EmailField(max_length=254, verbose_name='评论邮箱')),
                ('pl_web', models.CharField(max_length=50, verbose_name='评论网站')),
                ('pl_count', models.TextField(verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '回复信息',
                'verbose_name_plural': '回复信息',
            },
        ),
    ]
